### ISSUE TITLE
Checking for file on SD to "wake up"

### ISSUE THREAD

**Issue by beniroquai** [beniroquai/Matchboxscope#2]
@ethanjli a use scenario where a user do not need to recompile and upload the code would be to check for a file that is generated on the SD card and can be deleted after data downloading. 
What do you think?

**Comment by ethanjli** [comment]
Great idea - if I'm understanding you correctly, the device would look for a "REFOCUS" file on the SD card on each wake-up; if it finds that file, then it will go back into refocus mode.

**Comment by beniroquai** [comment]
Yes. Sorry :D
