### ISSUE TITLE
[FEATURE] Compile code as `.bin` using github actions

### ISSUE THREAD

**Issue by beniroquai** [beniroquai/Matchboxscope#7]
Since we have OTA and don'T want to overload the user with difficult library setup in Arduino IDE it would be great to build the binaries and provide it as releases. 
See here: https://github.com/openUC2/UC2-REST/actions

@ethanjli do you have any experience on how to move the artifact to a potential release?

**Comment by beniroquai** [comment]
Copy-pasted code from UC2-REST here
https://github.com/beniroquai/Matchboxscope/blob/master/.github/workflows/compileBinary.yml

Trying to compile now. Needs tweaks.

**Comment by ethanjli** [comment]
I'm not familiar with methods for uploading binaries to the ESP32, but I'd normally expect it to require running something in the command line, e.g. `esptool.py`. There may be some GUIs available, e.g. a Google search returned http://esphome.github.io/esp-web-tools/

**Comment by beniroquai** [comment]
Works now. BIN's will be available in the build artifacts.
